# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BKGGeocoder
                                 A QGIS plugin
 uses BKG geocoding API to geocode adresses
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-10-19
        copyright            : (C) 2018 by GGR
        email                : franke@ggr-planung.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import sys
import os
from qgis.gui import QgisInterface

def classFactory(iface: QgisInterface):
    '''
    load BKG geocoder plugin
    '''
    # workaround for package management, otherwise QGIS python would
    # look for packages in wrong folder,
    # requires restart on updating the plugin, because cached python files
    # are not cleared properly
    sys.path.append(os.path.dirname(os.path.abspath(__file__)))
    from .bkg_geocoder_main import BKGGeocoderPlugin
    return BKGGeocoderPlugin(iface)
